# Site Configuration

# baseURL is the root URL of my site - changes to your custom domain later
baseURL = 'https://ianwilder.dev'

# Language and locale settings
locale = 'en-us'

# My site's name - appears in browser tab and header
title = 'Ian Wilder'

# Tells Hugo which theme folder to use
theme = 'PaperMod'

# PaperMod specific parameters
[params]

# Foring dark theme and disabling theme toggle
defaultTheme = 'dark'
disableThemeToggle = true

# Site description used in metadata and SEO
description = "Cybersecurity Professional"

# Enables profile mode on the homepage
profileMode.enabled = true

# Profile Image Settings
profileMode.imageURL = "websiteProfile.png"
profileMode.imageTitle = "Ian Wilder"
profileMode.imageWidth = 150
profileMode.imageHeight = 150

# Profile mode title and subtitle
profileMode.title = "Ian Wilder"
profileMode.subtitle = "US Navy | Cybersecurity Professional | Developer"

# Social icons displayed on the home page
# Each [[params.socialIcons]] block is one icon/link
[[params.socialIcons]]
    name = "github"
    url = "https://github.com/irwilder"

[[params.socialIcons]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/ian-wilder-b7b7123b2/"

[[params.socialIcons]]
    name = "hackthebox"
    url = "https://app.hackthebox.com/users/3599940"
# Navigation menu items
# weight controls the order - lower numbers appear first
[[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

[[menu.main]]
    name = "Certifications"
    url = "/certs/"
    weight = 2

[[menu.main]]
    name = "Resume"
    url = "/resume/"
    weight = 3
    